"""*******************************************************************
***************************************************************************
 UTECLayerTools


 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder
                              -------------------
        begin                : 2025-03-04
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Florian Ludwig
        email                : immerse-vowel-dole@duck.com
 ***************************************************************************

***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************
"""

import configparser
import contextlib
from collections.abc import Callable
from pathlib import Path
from typing import TYPE_CHECKING

from qgis.core import Qgis, QgsLayerTree, QgsMapLayer, QgsProject, QgsVectorLayer
from qgis.gui import QgisInterface
from qgis.PyQt.QtCore import (
    QCoreApplication,
    QObject,
    QSettings,
    QTimer,
    QTranslator,
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMenu,
    QToolButton,
)

from .modules import general as ge
from .modules import logs_and_errors as lae
from .modules.general import get_current_project
from .modules.geopackage import move_layers_to_gpkg
from .modules.layer_location import add_location_indicator
from .modules.main_interface import set_iface
from .modules.rename import rename_layers, undo_rename_layers
from .modules.resource_utils import resources
from .modules.shipping import prepare_layers_for_shipping

if TYPE_CHECKING:
    from qgis.gui import QgsLayerTreeView, QgsMessageBar


class UTECLayerTools(QObject):  # pylint: disable=too-many-instance-attributes
    """QGIS Plugin for actions on layers."""

    def __init__(self, iface: QgisInterface) -> None:
        """Initialize the plugin.

        Args:
            iface: An interface instance that allows interaction with QGIS.
        """
        super().__init__()
        self.project: QgsProject = get_current_project()
        self.iface: QgisInterface = iface
        self.msg_bar: QgsMessageBar | None = iface.messageBar()
        ge.iface = iface
        set_iface(iface)
        self.plugin_dir: Path = Path(__file__).parent
        self.actions: list = []
        self.plugin_menu: QMenu | None = None
        self.plugin_icon = resources.icons.plugin_main_icon
        self.translator: QTranslator | None = None
        self._model_reset_handler: Callable | None = None
        self.location_indicators: dict = {}

        # Read metadata to get the plugin name for UI elements
        self.plugin_name: str = "UTEC Layer Tools (dev)"
        metadata_path: Path = self.plugin_dir / "metadata.txt"
        if metadata_path.exists():
            config = configparser.ConfigParser()
            config.read(metadata_path)
            try:
                self.plugin_name = config.get("general", "name")
            except (configparser.NoSectionError, configparser.NoOptionError):
                lae.log_debug("Could not read name from metadata.txt", Qgis.Warning)

        self.menu: str = self.plugin_name

        # initialize translation
        locale = QSettings().value("locale/userLocale", "en")[:2]
        translator_path: Path = self.plugin_dir / "i18n" / f"{locale}.qm"

        if not translator_path.exists():
            lae.log_debug(f"Translator not found in: {translator_path}", Qgis.Warning)
        else:
            self.translator = QTranslator()
            if self.translator is not None and self.translator.load(
                str(translator_path)
            ):
                QCoreApplication.installTranslator(self.translator)
            else:
                lae.log_debug("Translator could not be installed.", Qgis.Warning)

    def add_action(  # noqa: PLR0913 # pylint: disable=too-many-arguments,too-many-positional-arguments
        self,
        icon: str | QIcon,
        button_text: str,
        callback: Callable,
        enabled_flag: bool = True,  # noqa: FBT001, FBT002
        add_to_menu: bool = True,  # noqa: FBT001, FBT002
        add_to_toolbar: bool = True,  # noqa: FBT001, FBT002
        tool_tip: str | None = None,
        parent=None,  # noqa: ANN001
    ) -> QAction:  # pyright: ignore[reportInvalidTypeForm]
        """Create and configure a QAction for the plugin.

        This helper method creates a QAction, connects it to a callback, and
        optionally adds it to the QGIS toolbar and the plugin's menu.

        Args:
            icon: Path to the icon or QIcon object.
            button_text: Text to be displayed for the action in menus.
            callback: The function to execute when the action is triggered.
            enabled_flag: Whether the action should be enabled by default.
            add_to_menu: If True, adds the action to the plugin's menu.
            add_to_toolbar: If True, adds the action to a QGIS toolbar.
            tool_tip: Optional tooltip text for the action.
            parent: The parent widget for the action, typically the QGIS main window.

        Returns:
            The configured QAction instance.
        """

        if isinstance(icon, str):
            icon = QIcon(icon)
        action = QAction(icon, button_text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if tool_tip is not None:
            action.setToolTip(tool_tip)

        if add_to_toolbar:
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self) -> None:  # noqa: N802
        """Create the menu entries and toolbar icons for the plugin."""

        # Create a menu for the plugin in the "Plugins" menu
        self.plugin_menu = QMenu(self.menu, self.iface.pluginMenu())
        if self.plugin_menu is None:
            # fmt: off
            error_msg: str = QCoreApplication.translate("RuntimeError", "Failed to create the plugin menu.")
            # fmt: on
            lae.raise_runtime_error(error_msg)

        self.plugin_menu.setToolTipsVisible(True)
        self.plugin_menu.setIcon(self.plugin_icon)

        # Add an action for moving layers
        # fmt: off
        # ruff: noqa: E501
        button: str = QCoreApplication.translate("Menu_Button", "Copy Selected Layers to Project's GeoPackage")
        tool_tip_text: str = QCoreApplication.translate("Menu_ToolTip", "<p><b>Copy Selected Layers to Project's GeoPackage</b></p><p><span style='font-weight:normal; font-style:normal;'>Selected layers or layers in selected groups are copied to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and added back from the GeoPackage to the top of the layer tree of the current project.</span></p>")
        # fmt: on
        move_action = self.add_action(
            icon=resources.icons.main_move,
            button_text=button,
            callback=self.move_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            tool_tip=tool_tip_text,
        )
        self.plugin_menu.addAction(move_action)

        # Add an action for renaming layers
        # fmt: off
        # ruff: noqa: E501     
        button: str = QCoreApplication.translate("Menu_Button", "Rename Selected Layers by Group Name")
        tool_tip_text: str = QCoreApplication.translate("Menu_ToolTip", "<p><b>Rename Selected Layers by Group Name</b></p><p><span style='font-weight:normal; font-style:normal;'>Selected layers or layers in selected groups are renamed according to their parent group names. If a layer is not in a group, it is not renamed.</span></p>")
        # fmt: on
        rename_action = self.add_action(
            icon=resources.icons.main_rename,
            button_text=button,
            callback=self.rename_selected_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Will be added to our custom menu
            add_to_toolbar=False,  # Avoid creating a separate toolbar button
            tool_tip=tool_tip_text,
        )
        self.plugin_menu.addAction(rename_action)

        # Add an action for undoing the last rename
        # fmt: off
        # ruff: noqa: E501
        button: str = QCoreApplication.translate("Menu_Button", "Undo Last Rename")
        tool_tip_text: str = QCoreApplication.translate("Menu_ToolTip", "<p><b>Undo Last Rename</b></p><p><span style='font-weight:normal; font-style:normal;'>Undoes the most recent layer renaming operation performed by this plugin.</span></p>")
        # fmt: on
        undo_rename_action = self.add_action(
            icon=resources.icons.main_undo,
            button_text=button,
            callback=self.undo_last_rename,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            tool_tip=tool_tip_text,
        )
        self.plugin_menu.addAction(undo_rename_action)

        # Add an action for renaming and moving layers
        # fmt: off
        # ruff: noqa: E501
        button: str = QCoreApplication.translate("Menu_Button", "Rename and Copy Selected Layers to Project's GeoPackage")
        tool_tip_text: str = QCoreApplication.translate("Menu_ToolTip", "<p><b>Rename and Copy Selected Layers to Project's GeoPackage</b></p><p><span style='font-weight:normal; font-style:normal;'>Selected layers or layers in selected groups are renamed according to their parent group names, then copied to the project's GeoPackage (a GeoPackage in the project folder with the same name as the project file) and then added back from the GeoPackage to the top of the layer tree of the current project.</span></p>")
        # fmt: on
        rename_move_action = self.add_action(
            icon=resources.icons.main_rename_move,
            button_text=button,
            callback=self.rename_and_move_layers,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            tool_tip=tool_tip_text,
        )
        self.plugin_menu.addAction(rename_move_action)

        # Add an action for preparing layers for shipping
        # fmt: off
        # ruff: noqa: E501
        button: str = QCoreApplication.translate("Menu_Button", "Prepare Selected Layers for Sending")
        tool_tip_text: str = QCoreApplication.translate("Menu_ToolTip", "<p><b>Prepare Selected Layers for Sending</b></p><p><span style='font-weight:normal; font-style:normal;'>Creates a 'Versand' folder with a GeoPackage containing the selected layers and a project file with the same styling.</span></p>")
        # fmt: on
        shipping_action = self.add_action(
            icon=resources.icons.main_send,
            button_text=button,
            callback=self.prepare_shipping,
            parent=self.iface.mainWindow(),
            add_to_menu=False,  # Added to custom menu
            add_to_toolbar=False,
            tool_tip=tool_tip_text,
        )
        self.plugin_menu.addAction(shipping_action)

        # Add the fly-out menu to the main "Plugins" menu
        if menu := self.iface.pluginMenu():
            menu.addMenu(self.plugin_menu)
        toolbar_button = QToolButton()
        toolbar_button.setIcon(self.plugin_icon)
        toolbar_button.setToolTip(self.plugin_name)
        toolbar_button.setMenu(self.plugin_menu)
        toolbar_button.setPopupMode(QToolButton.InstantPopup)
        toolbar_action = self.iface.addToolBarWidget(toolbar_button)
        self.actions.append(toolbar_action)

        # Create the location indicators for the location of the layer source data
        self._update_all_location_indicators()
        self.iface.initializationCompleted.connect(self._on_project_read)
        self.project.layerWasAdded.connect(self._on_layer_added)
        self.project.layerWillBeRemoved.connect(self._on_layer_removed)
        # Connect to the layer tree model's reset signal to handle reordering
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        if view and (model := view.model()):
            # Store the handler to ensure it can be disconnected correctly.
            self._model_reset_handler = lambda: QTimer.singleShot(
                0, self._on_layer_tree_model_reset
            )
            model.modelReset.connect(self._model_reset_handler)

    def unload(self) -> None:
        """Plugin unload method.

        Called when the plugin is unloaded according to the plugin QGIS metadata.
        """
        # Unregister the layer tree view indicator
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if view and root and self.location_indicators:
            self._clear_all_location_indicators()

        # Disconnect layer tree model signal
        if (
            (view := self.iface.layerTreeView())
            and (model := view.model())
            and self._model_reset_handler
        ):
            model.modelReset.disconnect(self._model_reset_handler)

        # Disconnect all project-level signals
        if self.project:
            with contextlib.suppress(Exception):
                self.iface.initializationCompleted.disconnect(self._on_project_read)
            with contextlib.suppress(Exception):
                self.project.layerWasAdded.disconnect()
            with contextlib.suppress(Exception):
                self.project.layerWillBeRemoved.disconnect(self._on_layer_removed)
            # Disconnect signals from individual layers
            for layer in self.project.mapLayers().values():
                self._disconnect_layer_signals(layer)

        # Remove toolbar icons for all actions
        for action in self.actions:
            self.iface.removeToolBarIcon(action)

        # Remove the plugin menu from the "Plugins" menu.
        if self.plugin_menu and (menu := self.iface.pluginMenu()):
            menu.removeAction(self.plugin_menu.menuAction())

        # Remove the translator
        if self.translator:
            QCoreApplication.removeTranslator(self.translator)

        self.actions.clear()
        self.plugin_menu = None

    # --- Location Indicators ---

    def _clear_all_location_indicators(self) -> None:
        """Remove all location indicators from the layer tree view."""
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if not view or not root or not self.location_indicators:
            return

        for layer, indicator in self.location_indicators.items():
            if node := root.findLayer(layer.id()):
                view.removeIndicator(node, indicator)

        self.location_indicators.clear()
        lae.log_debug("Location Indicators → Cleared all location indicators.")

    def _update_all_location_indicators(self) -> None:
        """Update location indicators for all layers in the project."""
        self._clear_all_location_indicators()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if not root:
            return
        for layer_node in root.findLayers():
            if layer_node and (map_layer := layer_node.layer()):
                self._add_indicator_for_layer(map_layer)

    def _remove_indicator_for_layer(self, layer: QgsMapLayer) -> None:
        """Remove the location indicator for a single layer.

        Args:
            layer: The layer to remove the indicator from.
        """
        view: QgsLayerTreeView | None = self.iface.layerTreeView()
        root: QgsLayerTree | None = self.project.layerTreeRoot()
        if not view or not root:
            return

        if layer in self.location_indicators:
            indicator = self.location_indicators[layer]
            if node := root.findLayer(layer.id()):
                view.removeIndicator(node, indicator)
            del self.location_indicators[layer]
            lae.log_debug(
                f"Location Indicators → '{layer.name()}' → indicator removed."
            )

    def _update_indicator_for_layer(self, layer_id: str) -> None:
        """Add or update a location indicator for a single layer.

        If an indicator already exists for the layer, it will be removed and
        re-created to reflect any changes in the layer's state (e.g.,
        becoming empty or non-empty).

        Args:
            layer_id: The ID of the layer to update the indicator for.
        """
        layer: QgsMapLayer | None = self.project.mapLayer(layer_id)
        if not layer:
            return

        self._remove_indicator_for_layer(layer)
        self._add_indicator_for_layer(layer)

        # Force a targeted repaint of the specific layer tree node.
        if (
            (view := self.iface.layerTreeView())
            and (model := view.layerTreeModel())
            and (root := self.project.layerTreeRoot())
            and (node := root.findLayer(layer.id()))
        ):
            model_index = model.node2index(node)
            model.dataChanged.emit(model_index, model_index)

    def _add_indicator_for_layer(self, layer: QgsMapLayer) -> None:
        """Add a location indicator for a single layer if it doesn't exist.

        Args:
            layer: The layer to add an indicator for.
        """
        if layer in self.location_indicators:
            # Indicator already exists, do nothing.
            return

        if indicator := add_location_indicator(self.project, self.iface, layer):
            self.location_indicators[layer] = indicator
            msg: str = f"Location Indicators → '{layer.name()}' → indicator added successfully."
            lae.log_debug(msg)
            self._connect_layer_signals(layer)

    def _connect_layer_signals(self, layer: QgsMapLayer) -> None:
        """Connect signals for a specific layer.

        For vector layers, this connects the `editingStopped` signal to trigger
        an indicator update when edits are saved.

        Args:
            layer: The layer to connect signals for.
        """
        if isinstance(layer, QgsVectorLayer):
            with contextlib.suppress(TypeError):
                layer.editingStopped.connect(
                    lambda: self._on_layer_modified(layer.id())
                )

    def _on_layer_modified(self, layer_id: str) -> None:
        """Handle modification of a layer (e.g., after saving edits).

        This is intended to be connected to signals like `editingStopped`.

        Args:
            layer_id: The ID of the modified layer.
        """
        layer: QgsMapLayer | None = self.project.mapLayer(layer_id)
        if not layer:
            return

        lae.log_debug(
            f"'{layer.name()}' → Location Indicators → Layer modified, "
            "queueing indicator update..."
        )
        # Use a single-shot timer to defer the update slightly.
        QTimer.singleShot(0, lambda: self._update_indicator_for_layer(layer_id))

    def _on_project_read(self) -> None:
        """Handle the projectRead signal after a project is loaded."""
        lae.log_debug("Project loaded, setting up all indicators and signals.")
        self._update_all_location_indicators()

    def _on_layer_tree_model_reset(self) -> None:
        """Handle the layer tree model's reset signal, e.g., on reorder."""
        # Avoid running this during project load, which is handled separately.
        if self.project.isLoading():
            return

        lae.log_debug("Layer tree reset detected, updating all indicators.")
        self._update_all_location_indicators()

    def _on_layer_added(self, layer: QgsMapLayer) -> None:
        """Handle the layerWasAdded signal.

        Args:
            layer: The layer that was added (may be invalid later).
        """
        # This now only handles layers added manually after a project is open.
        # The initial load is handled by _on_project_read.
        self._add_indicator_for_layer(layer)

    def _on_layer_removed(self, layer_id: str) -> None:
        """Handle the layerWillBeRemoved signal.

        Args:
            layer_id: The ID of the layer that will be removed.
        """
        if layer_to_remove := next(
            (layer for layer in self.location_indicators if layer.id() == layer_id),
            None,
        ):
            self._disconnect_layer_signals(layer_to_remove)
            self._remove_indicator_for_layer(layer_to_remove)

    def _disconnect_layer_signals(self, layer: QgsMapLayer) -> None:
        """Disconnect signals from a specific layer.

        This is crucial to prevent errors when the layer is removed.

        Args:
            layer: The layer to disconnect signals from.
        """
        if isinstance(layer, QgsVectorLayer):
            with contextlib.suppress(TypeError, RuntimeError):
                layer.editingStopped.disconnect()

    #
    #
    # --- Plugin actions ---

    def rename_selected_layers(self) -> None:
        """Call rename function from 'functions_rename.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_selected_layers)", icon="✨✨✨"
        )
        with contextlib.suppress(lae.CustomUserError, lae.CustomRuntimeError):
            rename_layers()

    def move_selected_layers(self) -> None:
        """Call move function from 'functions_geopackage.py'."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (move_selected_layers)", icon="✨✨✨"
        )
        with contextlib.suppress(lae.CustomUserError, lae.CustomRuntimeError):
            move_layers_to_gpkg()

    def undo_last_rename(self) -> None:
        """Call undo function from 'modules/rename.py'."""
        lae.log_debug("... STARTING PLUGIN RUN ... (undo_last_rename)", icon="✨✨✨")
        with contextlib.suppress(lae.CustomUserError, lae.CustomRuntimeError):
            undo_rename_layers()

    def rename_and_move_layers(self) -> None:
        """Combine the rename and move functions."""
        lae.log_debug(
            "... STARTING PLUGIN RUN ... (rename_and_move_layers)", icon="✨✨✨"
        )
        with contextlib.suppress(lae.CustomUserError, lae.CustomRuntimeError):
            rename_layers()
            move_layers_to_gpkg()

    def prepare_shipping(self) -> None:
        """Call shipping function from 'modules/shipping.py'."""
        lae.log_debug("... STARTING PLUGIN RUN ... (prepare_shipping)", icon="✨✨✨")
        with contextlib.suppress(lae.CustomUserError, lae.CustomRuntimeError):
            prepare_layers_for_shipping()
